name: File Change Detection

on:
    push:
        paths:
            - 'README.md'

jobs:
    file-change-detection:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Notify file change
              if: github.ref == 'refs/heads/main'
              run: |
                  echo "A file change has been detected on the main branch."
                  echo "Changed files: ${{ github.event.commits[0].modified }}"